### ISSUE TITLE
JHU Test Fixtures

### ISSUE THREAD

**Issue by ewlarson** [jhu-sheridan-libraries/geoblacklight#1]
We need a few representative test fixtures for JHU. These fixtures are GBL JSON files and should work as representative items for your collection, or for custom features you need tested.

Example fixtures from the BTAA project are here:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/tree/develop/spec/fixtures/solr_documents

The README in that directory helps illustrate the reason each fixture is present.

**Comment by mjanowiecki** [comment]
Hi Eric,
I've attached the sample json files. I've validated them, but let me know if you have any trouble uploading them or find errors. 
[samplejson.zip](https://github.com/jhu-sheridan-libraries/geoblacklight/files/4224732/samplejson.zip)

**Comment by ewlarson** [comment]
@mjanowiecki - Thanks for sending these along! Please let me know if you have any questions about the feedback below. I'm happy to chat via zoom/phone/slack further, too.

----

I'm running into a couple of issues trying to import these documents into Solr. The errors seem pretty simple to fix, but also look like each document in the zip file might have the same issues.

Using the first document here as an example: 0ade4b5e-b3b3-4949-86ab-a83277d6e35b 

### solr_geom values 
This document's solr_geom ENVELOPE values are out of sequence. Solr needs a string in WKT/CQL ENVELOPE syntax, which is minX, maxX, maxY, minY order.

The order you have in the document is:
```
ENVELOPE(-77.311635, 39.348365, -76.787243, 39.720769)
```

When I import the doc with that order I see this error:

```txt
Error adding field 'solr_geom'='ENVELOPE(-77.311635, 39.348365, -76.787243, 39.720769)' msg=Unable to parse shape given formats "lat,lon", "x y" or as WKT because org.locationtech.spatial4j.exception.InvalidShapeException: maxY must be >= minY: 39.720769 to -76.787243 input: ENVELOPE(-77.311635, 39.348365, -76.787243, 39.720769)
```

The order that looks correct to me is:
```
ENVELOPE(-77.311635, -76.787243, 39.720769, 39.348365)
```

### dct_references_s
The values in this field look fine, however GeoBlacklight needs this field to be "stringified" json. We'll need to further escape the values here into a single string.

Instead of:
```json
  "dct_references_s": "{'http://schema.org/url': 'http://jhir.library.jhu.edu/handle/1774.2/32814', 'http://schema.org/downloadUrl': 'http://jscholarship.library.jhu.edu/handle/1774.2/32814/p.42-43 Franklin, Hampstead, New Windsor.jpg'}",
```

We'll need it to look like:
```json
  "dct_references_s": "{\"http://schema.org/url\": \"http://jhir.library.jhu.edu/handle/1774.2/32814\", \"http://schema.org/downloadUrl\": \"http://jscholarship.library.jhu.edu/handle/1774.2/32814/p.42-43 Franklin, Hampstead, New Windsor.jpg\"}",
```

### Fixed Example 

Here's a version of the document including these fixes that imports correctly for me:

```json
{
  "dc_identifier_s": "http://hopkinsgeoportal/0ade4b5e-b3b3-4949-86ab-a83277d6e35b",
  "dc_rights_s": "Public",
  "dc_title_s": "Franklin District No. 9, Hampstead, New Windsor, and Winfield P.O., 1877",
  "layer_slug_s": "0ade4b5e-b3b3-4949-86ab-a83277d6e35b",
  "solr_geom": "ENVELOPE(-77.311635, -76.787243, 39.720769, 39.348365)",
  "solr_year_i": 1877,
  "dc_creator_sm": [
    "Lake, Griffing, & Stevenson"
  ],
  "dc_description_s": "Maps of Franklin District No. 9, Hampstead, New Windsor, and Winfield P.O. from An Illustrated Atlas of Carroll County, Maryland by Lake, Griffing, & Stevenson.",
  "dc_format_s": "Mixed",
  "dc_language_sm": [
    "English"
  ],
  "dc_publisher_sm": [
    "Lake, Griffing, & Stevenson"
  ],
  "dc_source_sm": [
    "13eebc92-05c2-4f50-8b8e-a22f057e596f"
  ],
  "dc_subject_sm": [
    "Planning and Cadastral",
    "Atlases"
  ],
  "dc_type_s": "Image",
  "dct_references_s": "{\"http://schema.org/url\": \"http://jhir.library.jhu.edu/handle/1774.2/32814\", \"http://schema.org/downloadUrl\": \"http://jscholarship.library.jhu.edu/handle/1774.2/32814/p.42-43 Franklin, Hampstead, New Windsor.jpg\"}",
  "dct_spatial_sm": [
    "District 9, Franklin, Maryland, United States",
    "Hampstead, Maryland, United States",
    "New Windsor, Maryland, United States",
    "Winfield, Maryland, United States"
  ],
  "dct_temporal_sm": [
    "1877"
  ],
  "layer_geom_type_s": "Image",
  "suppressed_b": "False",
  "dct_provenance_s": "Johns_Hopkins",
  "geoblacklight_version": "1.0"
}
```

### Screenshot of Fixed Example

![Franklin District No  9  Hampstead  New Windsor  and Winfield P O   1877 - JHU GeoPortal](https://user-images.githubusercontent.com/69827/74851081-5fc3e300-5300-11ea-8d2b-8c1cdd96a8c1.png)

**Comment by mjanowiecki** [comment]
Hi-- that all seems totally fixable. It might take me an hour or two to edit my python script and produce these again, but I'll try to get these back to you as quick as possible.

Thank you so much for this feedback.

**Comment by mjanowiecki** [comment]
I think these are fixed, they look good from my end. Let me know if not. 
[samples_edited.zip](https://github.com/jhu-sheridan-libraries/geoblacklight/files/4226402/samples_edited.zip)

**Comment by ewlarson** [comment]
These are all indexing correctly now. Thanks for updating them so quickly!

I have added these docs to:
https://github.com/jhu-sheridan-libraries/geoblacklight/tree/master/spec/fixtures/solr_documents/jhu_documents 

This places them directly within the repository for source control, but it also allows them to be optionally indexed via a rake task:

```
bundle exec rake jhu:index_jhu_fixtures
```
----

I assume you will be adding [B1G metadata elements](https://sites.google.com/umn.edu/btaa-gdp/about/project-documents/metadata-guides/metadata-profile-of-geoblacklight-schema?authuser=0) to these documents over time. Here are a couple suggestions to enhance these fixtures, to leverage features within the codebase:

#### dct_provenance_s
Values here can just be "Johns Hopkins", with no underscore necessary. 

#### b1g_centroid_ss
Documents with this value will display in search results map clusters

#### b1g_date_range_drsim
Documents with a date range value will better match date range queries

**Comment by ewlarson** [comment]
Found a couple more issues here

- - - -

Looks like this title could be spaced better:

* ace11792-fca6-4c3a-a814-e7093de4deda

Found errors in the IIIF key/value in dct_references_s for:

* df152b1c-6bc0-485e-9a07-271a22adf80f
* fcb4e970-e54a-4778-876c-f595fe3878d9
* 2b50b898-93a8-44c4-8f3a-1810ab72e8a0
* fbdbf577-0033-4979-922f-1e7d3f8d056a
* 67f3bee7-01b7-4bcf-86ed-86462952cebc
* c8003de7-ed22-4813-82ce-b9d63ad572f2
* 9cb90240-9d5e-4cb4-9225-ffd1513442ab

If you look at the "http://iiif.io/api/image" values, you'll see some curly quotes which are breaking the application's JSON.parse call.

```json
{
  "dc_identifier_s": "df152b1c-6bc0-485e-9a07-271a22adf80f",
  "dc_rights_s": "Public",
  "dc_title_s": "Bird's Eye View of the City of Annapolis, MD",
  "layer_slug_s": "df152b1c-6bc0-485e-9a07-271a22adf80f",
  "solr_geom": "ENVELOPE(-76.539535, -76.469805, 38.998867, 38.94302)",
  "solr_year_i": 1864,
  "dc_creator_sm": [
    "Magnus, Charles"
  ],
  "dc_description_s": "This image was produced from an original print copy held as part of the Baetjer Collection. In the spring of 2017 the Venable LLP law firm generously donated to the Sheridan Libraries most of the maps, views and prints in the Baetjer Collection. One print, color lithograph, hand colored; 38 x 43 cm.",
  "dc_format_s": "Mixed",
  "dc_language_sm": [
    "English"
  ],
  "dc_publisher_sm": [
    "Magnus, Charles"
  ],
  "dc_subject_sm": [
    "Imagery and Base Maps"
  ],
  "dc_type_s": "Image",
  "dct_references_s": "{\"http://schema.org/url\": \"http://jhir.library.jhu.edu/handle/1774.2/61866\", \"http://schema.org/downloadUrl\": \"http://jscholarship.library.jhu.edu/handle/1774.2/61866/V430.jpg\", \"http://iiif.io/api/image’: ‘https://image.library.jhu.edu/iiif/js%2F1774.2%2F61866%2FV430/’}",
  "dct_spatial_sm": [
    "Annapolis, Maryland, United States"
  ],
  "dct_temporal_sm": [
    "1864"
  ],
  "layer_geom_type_s": "Image",
  "suppressed_b": false,
  "dct_provenance_s": "Johns_Hopkins",
  "geoblacklight_version": "1.0",
  "_version_": 1658988232952512500,
  "timestamp": "2020-02-19T17:47:46.934Z",
  "solr_bboxtype__minX": -76.539535,
  "solr_bboxtype__minY": 38.94302,
  "solr_bboxtype__maxX": -76.469805,
  "solr_bboxtype__maxY": 38.998867
}
```

**Comment by mjanowiecki** [comment]
I'll have to investigate how to make the uuid spacing better, those were just autogenerated.

Thanks for catching that curly quote error-- those little guys are the worst. Would you like me to regenerate the json files for those and fix the errors? I can do that this morning if it wouldn't be too much hassle/time for you to upload the new files.

**Comment by ewlarson** [comment]
Sorry for the confusion! I didn't mean the UUID was awkward, but the dc_title_s attribute for that record has a space typo in it. Lots of child documents for that record, so you see the bad title on many pages.

Please go ahead and regenerate them. It's absolutely easy to upload and index the new files.

**Comment by mjanowiecki** [comment]
Ok, that makes more sense. Apologies, I think I need more coffee. Update files coming your way.

**Comment by mjanowiecki** [comment]
I've attached the edited files here. I couldn't find c8003de7-ed22-4813-82ce-b9d63ad572f2 though -- is that possibly an old id from the first, unedited json files? 
[samples_edited2.zip](https://github.com/jhu-sheridan-libraries/geoblacklight/files/4231190/samples_edited2.zip)

**Comment by ewlarson** [comment]
Closing. Completed during the [February Winter Code Sprint](https://github.com/jhu-sheridan-libraries/geoblacklight/projects/1).
