### ISSUE TITLE
Homepage Customization

### ISSUE THREAD

**Issue by ewlarson** [jhu-sheridan-libraries/geoblacklight#15]
Homepage design should match UI mockup.

**Comment by ewlarson** [comment]
## Mockup
![Homepage Hackerman](https://user-images.githubusercontent.com/69827/74264857-0ab41b80-4cc7-11ea-9033-bade175a98e6.jpg)

**Comment by ewlarson** [comment]
## Current Screenshot
![jhu_geoblacklight_homepage](https://user-images.githubusercontent.com/69827/74264922-28818080-4cc7-11ea-90ec-9d2d1d4ae70c.png)

**Comment by prairieskygal** [comment]
Hi Eric! Sorry I missed meeting you yesterday, I plan to be on the call tomorrow. This homepage is looking great. There are a couple of things that stand out to me: 

- The font should be Gentona. I send the webfont CSS to where you can link to the files that we are hosting. Please let me know if you have issues making that work.
- The spacing around the logo in the header is a bit off. The most important factor here is that the logo needs more space around it on the bottom and right, and it can be smaller if need be. Ideally the spacing will be the same on all 4 sides, and then the spacing between the vertical line and the word "Geoportal" would match the spacing between the edge of the logo and vertical line.
- The header font and logo are black in the mockup, but the blue is fine if Mara and Reina like it
- You can probably remove the menu items in the header, unless Mara and Reina have content they know they want there

Thanks!
Jessica

**Comment by ewlarson** [comment]
Thanks @prairieskygal 

### Webfont
I have another issue open for Gentona ( #14 ). I'll try and pull the fonts directly from your CSS.

### Logo
Yeah, I wasn't exactly sure what asset to use there. I'll swap in the black one and try to equalize the spacing. I'll make things black, too.

### Menu Items
Very easy to remove and/or replace if necessary. I'll pull them from the design for now.

**Comment by reinacmurray** [comment]
Mara and I like the idea of having "About", "Contact" and "Help". We'll start working for content on those, does that sound good?

**Comment by ewlarson** [comment]
- [X] Gentona
- [X] Brand Spacing
- [X] Black Logo
- [X] Removed top header menu items
- [X] Header and footer moved to container-fluid
- [ ] Remove GBL Menu Items (Bookmarks, History, Login)
- [ ] Add JHU Menu Items (About, Contact, Help)

## Current screenshot

![jhu_geoblacklight_homepage](https://user-images.githubusercontent.com/69827/74280165-d9951480-4ce1-11ea-9d0c-d7706e777621.png)

**Comment by ewlarson** [comment]
Closing. Completed during the [February Winter Code Sprint](https://github.com/jhu-sheridan-libraries/geoblacklight/projects/1).
